# Generated by Django 6.0.2 on 2026-02-19 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Snapshot of username in case user is deleted', max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('REGISTER', 'User Registration'), ('LOGOUT', 'User Logout'), ('DELETE_USER', 'Delete User'), ('UPDATE_USER', 'Update User'), ('CHANGE_PASSWORD', 'Change Password'), ('TOGGLE_ACTIVATION', 'Toggle User Activation'), ('OTHER', 'Other Action')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
