# Generated by Django 6.0.2 on 2026-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('OWNER', 'Owner')], default='STUDENT', max_length=20),
        ),
    ]
