from books.models import Author, Category, Book

# Core seed data (title, author, category)
data = [
    ("To Kill a Mockingbird", "Harper Lee", "Classics"),
    ("1984", "George Orwell", "Classics"),
    ("Pride and Prejudice", "Jane Austen", "Classics"),
    ("The Great Gatsby", "F. Scott Fitzgerald", "Classics"),
    ("Moby Dick", "Herman Melville", "Classics"),
    ("War and Peace", "Leo Tolstoy", "Classics"),
    ("Jane Eyre", "Charlotte Bronte", "Classics"),
    ("Crime and Punishment", "Fyodor Dostoevsky", "Classics"),
    ("Catcher in the Rye", "J.D. Salinger", "Classics"),
    ("Lord of the Rings", "J.R.R. Tolkien", "Fantasy"),
    ("The Hobbit", "J.R.R. Tolkien", "Fantasy"),
    ("Harry Potter and the Sorcerers Stone", "J.K. Rowling", "Fantasy"),
    ("A Game of Thrones", "George R.R. Martin", "Fantasy"),
    ("Name of the Wind", "Patrick Rothfuss", "Fantasy"),
    ("Mistborn", "Brandon Sanderson", "Fantasy"),
    ("Dune", "Frank Herbert", "Sci-Fi"),
    ("Foundation", "Isaac Asimov", "Sci-Fi"),
    ("Neuromancer", "William Gibson", "Sci-Fi"),
    ("Enders Game", "Orson Scott Card", "Sci-Fi"),
    ("The Martian", "Andy Weir", "Sci-Fi"),
    ("Fahrenheit 451", "Ray Bradbury", "Sci-Fi"),
    ("Brave New World", "Aldous Huxley", "Sci-Fi"),
    ("The Road", "Cormac McCarthy", "Post-Apocalyptic"),
    ("Gone Girl", "Gillian Flynn", "Mystery"),
    ("Girl with the Dragon Tattoo", "Stieg Larsson", "Mystery"),
    ("A Study in Scarlet", "Arthur Conan Doyle", "Mystery"),
    ("Da Vinci Code", "Dan Brown", "Thriller"),
    ("Angels and Demons", "Dan Brown", "Thriller"),
    ("Silent Patient", "Alex Michaelides", "Thriller"),
    ("The Alchemist", "Paulo Coelho", "Fiction"),
    ("Sapiens", "Yuval Noah Harari", "Non-Fiction"),
    ("Educated", "Tara Westover", "Non-Fiction"),
    ("Atomic Habits", "James Clear", "Non-Fiction"),
    ("Thinking Fast and Slow", "Daniel Kahneman", "Non-Fiction"),
    ("Deep Work", "Cal Newport", "Productivity"),
    ("Clean Code", "Robert C. Martin", "Technology"),
    ("Pragmatic Programmer", "Andrew Hunt", "Technology"),
    ("Design Patterns", "Erich Gamma", "Technology"),
    ("Phoenix Project", "Gene Kim", "Technology"),
    ("AI A Modern Approach", "Stuart Russell", "Technology"),
    ("Intro to Algorithms", "Thomas H. Cormen", "Technology"),
    ("Grit", "Angela Duckworth", "Psychology"),
    ("Mans Search for Meaning", "Viktor Frankl", "Psychology"),
    ("Meditations", "Marcus Aurelius", "Philosophy"),
    ("Power of Now", "Eckhart Tolle", "Spirituality"),
    ("Rich Dad Poor Dad", "Robert Kiyosaki", "Finance"),
    ("Intelligent Investor", "Benjamin Graham", "Finance"),
    ("Thinking in Systems", "Donella Meadows", "Non-Fiction"),
    ("Lean Startup", "Eric Ries", "Business"),
    ("Zero to One", "Peter Thiel", "Business"),
    ("Purple Cow", "Seth Godin", "Business"),
    ("Good to Great", "Jim Collins", "Business"),
    ("Start with Why", "Simon Sinek", "Business"),
    ("Drive", "Daniel Pink", "Business"),
    ("Principles", "Ray Dalio", "Business"),
    ("Hooked", "Nir Eyal", "Business"),
    ("Made to Stick", "Chip Heath", "Business"),
    ("Cracking the Coding Interview", "Gayle Laakmann McDowell", "Technology"),
    ("Refactoring", "Martin Fowler", "Technology"),
    ("Domain Driven Design", "Eric Evans", "Technology"),
    ("Design of Everyday Things", "Don Norman", "Design"),
    ("Dont Make Me Think", "Steve Krug", "Design"),
    ("Sprint", "Jake Knapp", "Design"),
    ("Art of War", "Sun Tzu", "Classics"),
    ("The Kite Runner", "Khaled Hosseini", "Fiction"),
    ("Life of Pi", "Yann Martel", "Fiction"),
    ("Book Thief", "Markus Zusak", "Fiction"),
    ("Normal People", "Sally Rooney", "Fiction"),
    ("Midnight Library", "Matt Haig", "Fiction"),
    ("All the Light We Cannot See", "Anthony Doerr", "Fiction"),
    ("The Goldfinch", "Donna Tartt", "Fiction"),
    ("Fault in Our Stars", "John Green", "Fiction"),
    ("Vanishing Half", "Brit Bennett", "Fiction"),
    ("Where the Crawdads Sing", "Delia Owens", "Fiction"),
    ("Project Hail Mary", "Andy Weir", "Sci-Fi"),
    ("Klara and the Sun", "Kazuo Ishiguro", "Sci-Fi"),
    ("Station Eleven", "Emily St. John Mandel", "Post-Apocalyptic"),
    ("Invisible Life of Addie LaRue", "V.E. Schwab", "Fantasy"),
    ("Circe", "Madeline Miller", "Fantasy"),
    ("Song of Achilles", "Madeline Miller", "Fantasy"),
    ("Shadow of the Wind", "Carlos Ruiz Zafon", "Mystery"),
    ("Cloud Atlas", "David Mitchell", "Fiction"),
    ("Pillars of the Earth", "Ken Follett", "Historical"),
    ("Wolf Hall", "Hilary Mantel", "Historical"),
    ("Gentleman in Moscow", "Amor Towles", "Historical"),
    ("Beloved", "Toni Morrison", "Classics"),
    ("Handmaids Tale", "Margaret Atwood", "Dystopian"),
    ("Never Let Me Go", "Kazuo Ishiguro", "Dystopian"),
    ("Parable of the Sower", "Octavia Butler", "Dystopian"),
    ("Kindred", "Octavia Butler", "Historical"),
    ("Water Dancer", "Ta-Nehisi Coates", "Historical"),
    ("Hidden Figures", "Margot Lee Shetterly", "Non-Fiction"),
    ("Immortal Life of Henrietta Lacks", "Rebecca Skloot", "Non-Fiction"),
    ("Born a Crime", "Trevor Noah", "Non-Fiction"),
    ("Becoming", "Michelle Obama", "Non-Fiction"),
]

# Pad to at least 100 entries
while len(data) < 100:
    n = len(data) + 1
    data.append((f"Library Picks Vol {n}", "LMS Editorial", "General"))

created = 0
for idx, (title, author_name, category_name) in enumerate(data, start=1):
    author, _ = Author.objects.get_or_create(name=author_name)
    category, _ = Category.objects.get_or_create(name=category_name)
    isbn = f"AUTO-{idx:04d}"
    defaults = {
        "title": title,
        "author": author,
        "category": category,
        "quantity": 5,
        "available_count": 5,
        "description": "",
    }
    _, made = Book.objects.update_or_create(isbn=isbn, defaults=defaults)
    created += 1 if made else 0

print(f"processed {len(data)} books; created {created}")
